version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password 
      POSTGRES_DB: fuel_market_db
    networks:
      - data-tier
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_admin -d fuel_market_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  io-service:
    image: io-service-local
    build: 
      context: ../io-service
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password
      POSTGRES_HOST: postgres-db
      POSTGRES_DB: fuel_market_db
    networks:
      - app-tier
      - data-tier
    ports:
      - "8000:8000"
    depends_on:
      postgres-db:
        condition: service_healthy

  scraper-service:
    image: scraper-service-local
    build:
      context: ../scraper-service
    environment:
      IO_SERVICE_URL: http://io-service:8000 
    networks:
      - app-tier
    ports:
      - "8001:8001"
    depends_on:
      - io-service

  db-util:
    image: adminer
    restart: always
    networks:
      - data-tier
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

volumes:
  pg_data:

networks:
  front-tier:
    driver: bridge 
  app-tier:
    driver: bridge
  data-tier:
    driver: bridge