version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password 
      POSTGRES_DB: fuel_market_db
    networks:
      - data-tier
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_admin -d fuel_market_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  io-service:
    image: io-service-local
    build: 
      context: ../io-service
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password
      POSTGRES_HOST: postgres-db
      POSTGRES_DB: fuel_market_db
    networks:
      - app-tier
      - data-tier
    depends_on:
      postgres-db:
        condition: service_healthy

  scraper-service:
    image: scraper-service-local
    build:
      context: ../scraper-service
    environment:
      IO_SERVICE_URL: http://io-service:8000 
    networks:
      - app-tier
    depends_on:
      - io-service

  auth-service:
    image: auth-service-local
    build:
      context: ../auth-service
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password
      POSTGRES_HOST: postgres-db
      POSTGRES_DB: fuel_market_db
    networks:
      - app-tier
      - data-tier
    depends_on:
      postgres-db:
        condition: service_healthy

  db-util:
    image: adminer
    restart: always
    networks:
      - data-tier
    depends_on:
      - postgres-db

  kong:
    image: kong:latest
    user: "root"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
      - ./kong-config:/opt/kong
    networks:
      - app-tier
    ports:
      - "80:8000"   
      - "8443:8443"
    depends_on:
      - auth-service
      - io-service
      - scraper-service

volumes:
  pg_data:

networks:
  front-tier:
    driver: bridge 
  app-tier:
    driver: bridge
  data-tier:
    driver: bridge